trainer:
  settings:
    accelerator: gpu
    devices: [0]

workflow:
  name: SupervisedLearningV2

  components:
    model:
      name: UNet
      args:
        spatial_dims: 2
        in_channels: 1
        out_channels: 1
        channels: [32, 64, 128]
        strides: [2, 2]

    post_transforms:
      validation:
      - name: Activationsd
        args:
          keys: preds
          sigmoid: True
      - name: AsDiscreted
        args:
          keys: preds
          threshold: 0.5

    metrics:
      validation:
      - name: MONAIAdapter
        log_label: val_meandice
        args:
          name: DiceMetric

data:
  name: DecathlonDataModule

  settings:
    data_root: data
    data_list: data/datalist.json

  validation:
    data_list_key: valid
    transforms:
    - name: LoadImaged
      args:
        keys: [image, label]
        image_only: True
    - name: EnsureChannelFirstd
      args:
        keys: [image, label]
    - name: ScaleIntensityd
      args:
        keys: [image]
    - name: AsDiscreted
      args:
        keys: [label]
        threshold: 0.5
    - name: EnsureTyped
      args:
        keys: [image, label]
        dtype: float32
        track_meta: False

    dataset:
      name: Dataset

    dataloader:
      name: DataLoader
      args:
        batch_size: 1
        pin_memory: False
        num_workers: 8
