trainer:
  settings:
    accelerator: gpu
    devices: [0]

    max_epochs: &max_epochs 10

  callbacks:
    - name: ModelCheckpoint
      args:
        filename: best_model
        monitor: val_meandice
        mode: max

workflow:
  name: SupervisedLearningV2

  settings:
    scheduler:
      interval: epoch
      frequency: 1

  components:
    model:
      name: UNet
      args:
        spatial_dims: 2
        in_channels: 1
        out_channels: 1
        channels: [32, 64, 128]
        strides: [2, 2]

    loss:
    - name: DiceLoss
      input_keys: [preds, label]
      args:
        sigmoid: True

    optimizer:
      name: AdamW
      args:
        lr: 3.0e-4
        weight_decay: 1.0e-5

    scheduler:
      name: CosineAnnealingWarmRestarts
      args:
        T_0: *max_epochs

    post_transforms:
      training:
      - name: Activationsd
        args:
          keys: preds
          sigmoid: True
      - name: AsDiscreted
        args:
          keys: preds
          threshold: 0.5

      validation:
      - name: Activationsd
        args:
          keys: preds
          sigmoid: True
      - name: AsDiscreted
        args:
          keys: preds
          threshold: 0.5

    metrics:
      training:
      - name: MONAIAdapter
        log_label: train_meandice
        args:
          name: DiceMetric

      validation:
      - name: MONAIAdapter
        log_label: val_meandice
        args:
          name: DiceMetric

data:
  name: DecathlonDataModule

  settings:
    data_root: data
    data_list: data/datalist.json

  training:
    data_list_key: train
    transforms:
    - name: LoadImaged
      args:
        keys: [image, label]
    - name: EnsureChannelFirstd
      args:
        keys: [image, label]
    - name: ScaleIntensityd
      args:
        keys: [image]
    - name: RandAffined
      args:
        keys: [image, label]
        prob: 1.0
        rotate_range: 0.25
        shear_range: 0.2
        translate_range: 0.1
        scale_range: 0.2
        padding_mode: zeros
    - name: AsDiscreted
      args:
        keys: [label]
        threshold: 0.5
    - name: EnsureTyped
      args:
        keys: [image, label]
        dtype: float32
        track_meta: False

    dataset:
      name: CacheDataset
      args:
        cache_rate: 1.0
        num_workers: 8

    dataloader:
      name: DataLoader
      args:
        batch_size: 8
        shuffle: True
        pin_memory: False
        num_workers: 16

  validation:
    data_list_key: valid
    transforms:
    - name: LoadImaged
      args:
        keys: [image, label]
        image_only: True
    - name: EnsureChannelFirstd
      args:
        keys: [image, label]
    - name: ScaleIntensityd
      args:
        keys: [image]
    - name: AsDiscreted
      args:
        keys: [label]
        threshold: 0.5
    - name: EnsureTyped
      args:
        keys: [image, label]
        dtype: float32
        track_meta: False

    dataset:
      name: CacheDataset
      args:
        cache_rate: 1.0
        num_workers: 8

    dataloader:
      name: DataLoader
      args:
        batch_size: 20
        pin_memory: False
        num_workers: 8
