workflow:
  components:
    inferer:
      args:
        overlap: 0.5
        roi_size:
        - 96
        - 96
        - 96
        sw_batch_size: 4
      name: SlidingWindowInferer
    loss:
      args:
        include_background: true
        softmax: true
        to_onehot_y: true
      name: DiceCELoss
    model:
      args:
        in_channels: 1
        out_channels: 3
      name: SegResNet
    optimizer:
      args:
        lr: 0.0001
      name: AdamW
    post_transforms:
      test:
      - args:
          argmax: true
          keys: preds
          num_classes: 3
        name: AsDiscreted
      - args:
          data_type: numpy
          keys:
          - preds
          - image_meta_dict
        name: EnsureTyped
      - args:
          keys:
          - preds
          meta_keys:
          - image_meta_dict
          mode: nearest
          output_dir: results
          output_ext: .nii.gz
          output_postfix: preds
          print_log: false
          separate_folder: false
          squeeze_end_dims: true
        name: SaveImaged
      training:
      - args:
          argmax:
          - true
          - false
          channel_dim: 1
          keys:
          - preds
          - label
          num_classes: 3
          to_onehot:
          - true
          - true
        name: AsDiscreted
        path: manafaln.transforms
      validation:
      - args:
          argmax:
          - true
          - false
          keys:
          - preds
          - label
          num_classes: 3
          to_onehot:
          - true
          - true
        name: AsDiscreted
      - args:
          channel_dim: 0
          keys:
          - preds
          - label
          output_postfixes:
          - background
          - pancreas
          - tumor
        name: SplitChanneld
      - args:
          dim: 0
          keys:
          - preds
          - label
        name: Unsqueezed
        path: manafaln.transforms
    scheduler:
      args:
        T_0: 2300
        T_mult: 10
        eta_min: 1.0e-05
      name: CosineAnnealingWarmRestarts
    training_metrics:
    - args:
        get_not_nans: false
        include_background: false
        reduction: mean
      log_label: train_meandice
      name: DiceMetric
      output_transform: 'lambda x: (x[''preds''], x[''label''])'
    - args:
        compute_sample: true
        get_not_nans: false
        include_background: false
        metric_name:
        - sensitivity
        - specificity
        - accuracy
        reduction: mean
      log_label:
      - train_sensitivity
      - train_specificity
      - train_accuracy
      name: ConfusionMatrixMetric
      output_transform: 'lambda x: (x[''preds''], x[''label''])'
    validation_metrics:
    - args:
        get_not_nans: false
        include_background: false
        reduction: mean
      log_label: val_meandice
      name: DiceMetric
      output_transform: 'lambda x: (x[''preds''], x[''label''])'
    - args:
        compute_sample: true
        get_not_nans: false
        include_background: false
        metric_name:
        - sensitivity
        - specificity
        - accuracy
        reduction: mean
      log_label:
      - val_sensitivity
      - val_specificity
      - val_accuracy
      name: ConfusionMatrixMetric
      output_transform: 'lambda x: (x[''preds''], x[''label''])'
  name: SupervisedSegmentation
  settings:
    decollate: true
    decollate_phases:
    - validation
    - test
    learning_rate: 0.0005
    num_classes: 3
    scheduler:
      frequency: 1
      interval: step
